{
 "title": "Decentrifi Usage",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average duration in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_get_claimables_aggregate_seconds_sum{container=\"defitrack-claimables\"}[$__rate_interval]) / rate(requests_get_claimables_aggregate_seconds_count[$__rate_interval])",
     "legendFormat": "claimables [synchronous]"
    },
    {
     "expr": "rate(ens_by_address_seconds_sum{container=\"defitrack-ens\"}[$__rate_interval]) / rate(ens_by_address_seconds_count[$__rate_interval])",
     "legendFormat": "ens by address"
    },
    {
     "expr": "rate(ens_by_name_seconds_sum{container=\"defitrack-ens\"}[$__rate_interval]) / rate(ens_by_name_seconds_count[$__rate_interval])",
     "legendFormat": "ens by name"
    }
   ]
  },
  {
   "title": "Average TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_get_claimables_aggregate_seconds_count{container=\"defitrack-claimables\"}[$__rate_interval])",
     "legendFormat": "claimables [synchronous]"
    },
    {
     "expr": "rate(ens_by_address_seconds_count{container=\"defitrack-ens\"}[$__rate_interval])",
     "legendFormat": "ens by address"
    },
    {
     "expr": "rate(ens_by_name_seconds_count{container=\"defitrack-ens\"}[$__rate_interval])",
     "legendFormat": "ens by name"
    }
   ]
  },
  {
   "title": "Average duration of calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(contract_interaction_seconds_sum[$__rate_interval]) / rate(contract_interaction_seconds_count[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Contract calls per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(contract_interaction_seconds_count[$__rate_interval])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}