apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: defitrack-service-monitors
  labels:
    release: prometheus
    app.kubernetes.io/instance: prometheus
  annotations:
    "meta.helm.sh/release-name": "prometheus"
    "meta.helm.sh/release-namespace": "default"
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      team: decentrifi
  endpoints:
    - port: http-traffic
      interval: 10s
      path: "/actuator/prometheus"